Update index.md
steno-aarhus/research pull request #104
Opened 2024-08-08 11:58 UTC by LotteArentoft

2024-08-12 10:48 UTC, lwjohnst86 requested changes
Thanks for the contribution! I noticed you used a lot of `<br>`. Could explain why you want those? Or were they something that was automatically added when you were typing?

In general, you rarely need or should use those. Instead, use either a list (Markdown lines that start with `-`) or as new paragraphs (create an empty line between two text).

I've removed most of them or converted some that you added into lists.

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
>  ([inger.hornbech\@rm.dk](mailto:inger.hornbech@rm.dk){.email}).
Nice! Since this is document is written with Markdown, instead of the HTML `<br>`, you can create a new line and have an empty line between the paragraphs:

```suggestion
registers you in BSK and gives you access.

The access card itself is picked up in the Photo Box (Krydspunkt J110, lokale J116-106), where you
will also have your picture taken.

To gain access to special locations (e.g. Cell culture) contact Inger Hornbech
([inger.hornbech\@rm.dk](mailto:inger.hornbech@rm.dk){.email}).
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +Freezer and/or refrigerated packages
```suggestion
you can both receive and send mail.

Freezer and/or refrigerated packages
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +<br>
```suggestion
| Att: YOUR NAME


```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +It is not possible to get uniforms with long sleeves, but thin
```suggestion
sleeves.

It is not possible to get uniforms with long sleeves, but thin
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +Used Uniforms/workwear must be placed in the blue
```suggestion
removed before leaving Level 4.

Used Uniforms/workwear must be placed in the blue
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +Contact Julie Knudsen,
```suggestion
bathing facilities.

Contact Julie Knudsen,
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +Therefore, pay attention to what is placed in fume Hoods from Wednesday to Thursday.
```suggestion
- You must be conscious and responsible when working with Chemicals.
- You are responsible for checking up on the Chemicals and handling them correctly.
- All Chemicals must be handled according to their Hazard Label.
- When handling Chemicals with Hazard Label, always use gloves and
work in fume hood or LAF bench.
- Always be aware about Chemical waste management.
- Make sure that there is a Chemical Risk
Assessment in your protocol before using any of the Hazard Labelt
Chemicals.
- Be aware that ventilation checks of fire dampers are ongoing from 6.00-6.30 every Thursday, which means that fume
hood / LAF benches do not work during that period. Therefore, pay attention to what is placed in fume Hoods from Wednesday to Thursday. 
```

I'm not really sure why you would like each sentence to have a break at the end. I am guessing that this set of sentences could instead be a list?

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +There is an LAF bench in both Chemical rooms with a precise balance.<br>
```suggestion
- There is an LAF bench in both Chemical rooms with a precise balance.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +In room A401-118 there is also a pH-meter and a magnetic stirrer.<br>
```suggestion
- In room A401-118 there is also a pH-meter and a magnetic stirrer.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
```suggestion
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
```suggestion

Here are some guidelines and things to consider:

```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
>  form (in Danish)](/files/bestilling-af-is.pdf).
```suggestion
You can pickup dry ice from room A101-113, level 1
or you can order via the Purchasing Department (Indkøbsafdelingen), AUH - use the [dry ice order
form (in Danish)](/files/bestilling-af-is.pdf).
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +Remember to mark the Chemical waste container with fraction, name and department.
```suggestion
- In the Chemical storage room A401-172 you can place the Chemical waste at the button in the cabinet with ventilation.
- Pick up MUST be booked before placing the chemical waste.
- Instructions are available on the trolley (in Danish).
- **Pay attention to waste
groups!!**
- Remember to mark the Chemical waste container with fraction, name and department.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +The second Dry-Autoclave can be used for both sterilization and for "burning" glassware for RNA/DNA
```suggestion
There is one small Wet-Autoclave and two Dry-Autoclaves in room A401-166
The Wet-Autoclave can be used for small instruments e.g.

One Dry-Autoclave is reserved for cell culture bottles etc. and will be
started approximately every other day.
The second Dry-Autoclave can be used for both sterilization and for "burning" glassware for RNA/DNA
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +kept out of there for min. 2 hours.<br>
```suggestion
kept out of there for min. 2 hours.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +All doors are fire-doors and they close automatically upon fire.<br>
```suggestion
All doors are fire-doors and they close automatically upon fire.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +All locked doors open so you can get in and out without access cards. <br>
```suggestion
All locked doors open so you can get in and out without access cards.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +hood / LAF benches do not work during that period.<br>
```suggestion
hood / LAF benches do not work during that period.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +starting work.<br>
```suggestion
starting work.

```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +<br>
```suggestion

```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +hood / LAF benches do not work during that period.<br>
```suggestion
hood / LAF benches do not work during that period.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +what is to be borrowed.<br>
```suggestion
what is to be borrowed.

```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +We have 3 Cell Culture Rooms, that are GMO Class I classified. <br>
```suggestion
We have 3 Cell Culture Rooms, that are GMO Class I classified.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +corridors.<br>
```suggestion
corridors.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +instructions, and content.<br>
```suggestion
instructions, and content.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +([henrikis\@rm.dk](mailto:henrikis@rm.dk){.email}). <br>
```suggestion
([henrikis\@rm.dk](mailto:henrikis@rm.dk){.email}).
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +yourself.<br>
```suggestion
yourself.

```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +A401-172.<br>
```suggestion
A401-172.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +    - *Hard plastic hazardous* in room A401-172.<br>
```suggestion
    - *Hard plastic hazardous* in room A401-172.
```

Using `<br>` isn't needed within a list

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +        well as room A401-172.<br>
```suggestion
        well as room A401-172.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +       Soft plastic is plastic such as bubble wrap, plastic bags, etc.<br>
```suggestion
       Soft plastic is plastic such as bubble wrap, plastic bags, etc.
```

2024-08-12 10:48 UTC, lwjohnst86 commented on onboarding/getting-started-plan-4/index.md
> +You will find it by > Hjælp til > affaldshåndtering > Affaldshåndbogen
```suggestion
In the Citrix RM system, you can enter Microsoft Edge and at the page for RM
you can use a help function to search for different waste fractions.
This guide is only in Danish.
You will find it by `> Hjælp til > affaldshåndtering > Affaldshåndbogen`    
```

2024-08-13 08:07 UTC, LotteArentoft commented
well... 😊 It's because I don't really know how to code in GitHub and I'm trying to do my best. I've googled that I can make an extra line by using <br>, but if it needs to be done differently, then of course I just must learn how 😊. I have made some changes, to make it easier or simpler to read, and then I have made some updates due to changes in the lab. You can just make the changes you suggest and then I can check it out and see if this was what I had in mind 😊

2024-08-13 08:13 UTC, lwjohnst86 approved these changes

2024-08-13 08:14 UTC, lwjohnst86 commented
@LotteArentoft great!! And that's awesome to hear 😁 I made the edits and will now put it on the website. You can check it soon to see if the page looks as you were expecting/hoping ☺️

2024-08-13 08:15 UTC, merged