How to set up studies - add ANY relevant info
steno-aarhus/research pull request #6
Opened 2021-02-03 07:35 UTC by sineknorr

2021-02-03 13:09 UTC, lwjohnst86 commented on Setting_up_a_study.RMD
> +```
This should be `-` minus symbol, not backtick \`

```suggestion
---
```

2021-02-03 13:12 UTC, lwjohnst86 requested changes
Great start!! I've made some suggested changes. Read them below.

2021-02-03 13:12 UTC, lwjohnst86 commented on Setting_up_a_study.RMD
> +```
```suggestion
---
```

2021-02-03 13:12 UTC, lwjohnst86 commented on Setting_up_a_study.RMD
> +      * Item 1.1 Preparing for a study
Nice first start! For markdown lists, you need to use either `*` or `-`, and don't need to put "Item 1.1" etc. Also, there should be an empty line before the list and should begin at the start of the line. The suggested change is below:

```suggestion

* Preparing for a study
```

2021-02-03 13:16 UTC, sineknorr commented on Setting_up_a_study.RMD
> +      * Item 1.1 Preparing for a study
> Nice first start! For markdown lists, you need to use either `*` or `-`, and don't need to put "Item 1.1" etc. Also, there should be an empty line before the list and should begin at the start of the line. The suggested change is below:

Ahhhh - makes sense - feel a bit stupid for not understanding what they ment with item.....:-)

2021-03-24 12:49 UTC, lwjohnst86 commented
Ah, this, right! Thanks @sineknorr I'll look over it later today.

2021-03-29 19:16 UTC, lwjohnst86 approved these changes
This is a great start! I was thinking as I was looking it over whether we want to write this as a more "narrative" style, with the perspective of someone just starting a new project. Like "first you need to do this, best to set it up like that, etc." And then afterwards provide a checklist at the end? Just something to think about.

2021-03-29 19:17 UTC, lwjohnst86 commented
@sineknorr for now, I'm going to accept what you've added and join it with the main files. Your own "sinekorr" branch will still be there, so you can keep working there on this.

2021-03-29 19:17 UTC, merged